heat_template_version: 2017-02-24

description: Plantilla de despliegue de los servidores de aplicacion

parameters:

  server_name:
    type: string
    description: Nombre del servidor

  flavor:
    type: string
    description: Flavor de la instancia
    default: m1.nano
    constraints:
      - allowed_values: [m1.nano, m1.tiny, m1.small, m1.large]
        description: Value must be one of m1.tiny, m1.small or m1.large
  
  image:
    type: string
    default: cirros-0.3.4-x86_64-vnx
    description: Nombre de la imagen

  private_net_name: 
    type: string 
    description: Nombre de la red privada 1

  private_subnet_name: 
    type: string 
    description: Nombre de la subred privada 1

  private_net_2_name: 
    type: string 
    description: Nombre de la red privada 2

  private_subnet_2_name: 
    type: string 
    description: Nombre de la subred privada 2

resources:

  app_server:
    type: OS::Nova::Server
    #depends_on: [ clave_generada ]
    properties:
      name: { get_param: server_name }
      image: { get_param: image }
      flavor: { get_param: flavor }
      #key_name: { get_resource: clave_generada }
      networks:
        - port: { get_resource: app_server_port0 }
        - port: { get_resource: app_server_port1 }

  app_server_port0:
    type: OS::Neutron::Port
    properties:
      network_id: { get_param: private_net_name }
      security_groups:
        - default
      fixed_ips:
        - subnet_id: { get_param: private_subnet_name }

  app_server_port1:
    type: OS::Neutron::Port
    properties:
      network_id: { get_param: private_net_2_name }
      security_groups:
        - default
      fixed_ips:
        - subnet_id: { get_param: private_subnet_2_name }
