heat_template_version: 2017-02-24

description: Plantilla de despliegue de los servidores de zookeeper

parameters:

  server_name:
    type: string
    description: Nombre del servidor

  flavor:
    type: string
    description: Flavor de la instancia
    default: m1.smaller
    constraints:
      - allowed_values: [m1.nano, m1.tiny, m1.smaller]
        description: Value must be one of m1.nano, m1.tiny, m1.smaller
  
  image:
    type: string
    default: zookeeper_image
    description: Nombre de la imagen

  private_net_name: 
    type: string 
    description: Nombre de la red privada 1

  private_subnet_name: 
    type: string 
    description: Nombre de la subred privada 1

  private_ip_address:
    type: string
    description: Direccion ip en la subred privada 1

resources:

  app_server:
    type: OS::Nova::Server
    #depends_on: [ clave_generada ]
    properties:
      name: { get_param: server_name }
      image: { get_param: image }
      flavor: { get_param: flavor }
      #key_name: { get_resource: clave_generada }
      user_data_format: RAW
      user_data: |
        #cloud-config
        runcmd:
          - [ mongod, --smallfiles]
      networks:
        - port: { get_resource: app_server_port0 }

  app_server_port0:
    type: OS::Neutron::Port
    properties:
      network_id: { get_param: private_net_name }
      security_groups:
        - open
      fixed_ips:
        - subnet_id: { get_param: private_subnet_name }
          ip_address: { get_param: private_ip_address }

outputs:
  first_address:
    description: Direccion IP en la red privada de la maquina
    value: { get_attr: [ app_server, first_address ] }
